FROM us-central1-docker.pkg.dev/project-6d7c1b56-cee5-450d-93e/cloud-run-source-deploy/pdf-to-html@sha256:6723754524d79b258eca55298b3fcf627bcd894075708de35ca31eb177111bbe
COPY scripts/parse-pdf.py scripts/pdf-heading-styles.py ./scripts/
