FROM us-central1-docker.pkg.dev/project-6d7c1b56-cee5-450d-93e/cloud-run-source-deploy/pdf-to-html@sha256:135dd38137335db79773129038cb352a9393a7c74ee9406aac43b2685b25b001
COPY scripts/pdf-heading-styles.py ./scripts/
COPY public/index.html ./public/
